-- TẠO CƠ SỞ DỮ LIỆU
CREATE DATABASE QLKHACHSAN;
GO

USE QLKHACHSAN;
GO

-- ==========================
-- BẢNG NHÂN VIÊN
-- ==========================
CREATE TABLE NHANVIEN (
    MANV INT IDENTITY(1,1) PRIMARY KEY,
    HOTEN NVARCHAR(30) NOT NULL,
    PHAI NCHAR(3) NOT NULL,
    NGAYSINH DATE NOT NULL,
    SDT NVARCHAR(12) NOT NULL,
    EMAIL NVARCHAR(100) NOT NULL,
    DIACHI NVARCHAR(100) NULL
);

-- ==========================
-- BẢNG LOẠI PHÒNG
-- ==========================
CREATE TABLE LOAIPHONG (
    MALOAIPHONG INT IDENTITY(1,1) PRIMARY KEY,
    TENLOAI NVARCHAR(30) NOT NULL,
    DONGIA INT NOT NULL
);

-- ==========================
-- BẢNG PHÒNG
-- ==========================
CREATE TABLE PHONG (
    MAP INT IDENTITY(1,1) PRIMARY KEY,
    TENPHONG NVARCHAR(30) NOT NULL,
    TINHTRANG INT NOT NULL,
    SOLUONGKHACHTOIDA INT NOT NULL,
    GHICHU TEXT NULL,
    MALOAIPHONG INT NOT NULL,
    SONGAYO INT NOT NULL,
    CONSTRAINT FK_PHONG_LOAIPHONG FOREIGN KEY (MALOAIPHONG)
        REFERENCES LOAIPHONG(MALOAIPHONG)
);

-- ==========================
-- BẢNG LOẠI KHÁCH
-- ==========================
CREATE TABLE LOAIKHACH (
    MALOAIKHACH INT IDENTITY(1,1) PRIMARY KEY,
    TENLOAIKHACH NCHAR(20)
);

-- ==========================
-- BẢNG KHÁCH HÀNG
-- ==========================
CREATE TABLE KHACHHANG (
    MAKH INT IDENTITY(1,1) PRIMARY KEY,
    TENKH NVARCHAR(30) NOT NULL,
    TUOI INT NOT NULL,
    TEL NVARCHAR(12) NOT NULL,
    DIACHIKH NVARCHAR(100),
    CMNDKH NVARCHAR(50) NOT NULL,
    MALOAIKHACH INT NOT NULL,
    MAP INT NOT NULL,
    CONSTRAINT FK_KHACHHANG_LOAIKHACH FOREIGN KEY (MALOAIKHACH)
        REFERENCES LOAIKHACH(MALOAIKHACH),
    CONSTRAINT FK_KHACHHANG_PHONG FOREIGN KEY (MAP)
        REFERENCES PHONG(MAP)
);

-- ==========================
-- BẢNG PHIẾU THUÊ
-- ==========================
CREATE TABLE PHIEUTHUE (
    MAPT INT IDENTITY(1,1) PRIMARY KEY,
    NGAYLAPPT DATETIME NOT NULL,
    MAKH INT NOT NULL,
    MAP INT NOT NULL,
    CCCD NVARCHAR(50) NOT NULL,
    CONSTRAINT FK_PHIEUTHUE_KHACHHANG FOREIGN KEY (MAKH)
        REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_PHIEUTHUE_PHONG FOREIGN KEY (MAP)
        REFERENCES PHONG(MAP)
);

-- ==========================
-- BẢNG HÓA ĐƠN
-- ==========================
CREATE TABLE HOADON (
    MAHD INT IDENTITY(1,1) PRIMARY KEY,
    SONGAYO INT NOT NULL,
    MANV INT NOT NULL,
    TONGTIEN INT NOT NULL,
    TENKH NVARCHAR(50) NOT NULL,
    TENPHONG NVARCHAR(50) NOT NULL,
    NGAYLAPHD DATETIME NOT NULL,
    NGAYDAT DATETIME NOT NULL,
    TYLEPHUTHU FLOAT NOT NULL,
    CCCD NVARCHAR(50) NOT NULL,
    CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY (MANV)
        REFERENCES NHANVIEN(MANV)
);

-- ==========================
-- BẢNG PHỤ THU
-- ==========================
CREATE TABLE PHUTHU (
    IDPhuthu INT IDENTITY(1,1) PRIMARY KEY,
    Giatriphuthu FLOAT NOT NULL
);

-- ==========================
-- BẢNG TÀI KHOẢN
-- ==========================
CREATE TABLE TAIKHOAN (
    MATKNV INT IDENTITY(1,1) PRIMARY KEY,
    TENTKNV NCHAR(40) NOT NULL,
    MKTK NCHAR(30) NOT NULL,
    MANV INT NOT NULL,
    CONSTRAINT FK_TAIKHOAN_NHANVIEN FOREIGN KEY (MANV)
        REFERENCES NHANVIEN(MANV)
);

-- ==========================
-- DỮ LIỆU MẪU
-- ==========================

INSERT INTO NHANVIEN (HOTEN, PHAI, NGAYSINH, SDT, EMAIL, DIACHI)
VALUES 
(N'Vũ Thanh Hải', N'Nam', '2001-12-07', N'0123456789', N'admin@gmail.com', N'Cầu Giấy'),
(N'admin2', N'Nam', '2000-02-02', N'01236544789', N'admin2@siu.edu.vn', N'Hà Đông');

INSERT INTO LOAIPHONG (TENLOAI, DONGIA)
VALUES (N'12', 120000),
       (N'25', 250000);

INSERT INTO PHONG (TENPHONG, TINHTRANG, SOLUONGKHACHTOIDA, GHICHU, MALOAIPHONG, SONGAYO)
VALUES (N'102', 2, 2, N'Dành cho khách hàng VIP', 1, 0),
       (N'103', 1, 2, N'Phòng có bồn', 2, 0),
       (N'104', 1, 2, NULL, 1, 0),
       (N'101', 1, 2, NULL, 1, 0);

INSERT INTO LOAIKHACH (TENLOAIKHACH)
VALUES (N'Trong Nước'), (N'Nước Ngoài');

INSERT INTO KHACHHANG (TENKH, TUOI, TEL, DIACHIKH, CMNDKH, MALOAIKHACH, MAP)
VALUES 
(N'Vũ Thanh Hải', 18, N'0123456789', N'Cầu Giấy', N'0002', 1, 1),
(N'ROSE', 21, N'554546', N'Anh', N'0001', 2, 1);

INSERT INTO PHUTHU (Giatriphuthu) VALUES (20);

INSERT INTO TAIKHOAN (TENTKNV, MKTK, MANV)
VALUES 
(N'admin@gmail.com', N'123456789', 1),
(N'admin2@siu.edu.vn', N'123456789', 2);

INSERT INTO HOADON (SONGAYO, MANV, TONGTIEN, TENKH, TENPHONG, NGAYLAPHD, NGAYDAT, TYLEPHUTHU, CCCD)
VALUES
(1, 1, 144000, N'Vũ Thanh Hải', N'102', '2025-10-04T10:56:28', '2025-10-04', 20, N'0002'),
(1, 1, 120000, N'ROSE', N'101', '2025-10-04T10:59:31', '2025-10-03', 0, N'0001'),
(0, 1, 0, N'ROSE', N'104', '2025-10-04T10:59:37', '2025-10-05', 0, N'0001');

ALTER TABLE PHONG
ALTER COLUMN GHICHU NVARCHAR(100) NULL;
select * from NHANVIEN
select * from TAIKHOAN
